# Generated by Django 5.2.7 on 2025-10-02 03:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tarefa_notas_tarefa_tempo_estimado_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='tempo_estimado',
            field=models.IntegerField(default=0, help_text='Tempo estimado em minutos (mínimo: 0)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
